### ISSUE TITLE
作者能提供预训练的模型吗

### ISSUE THREAD

**Issue by wn1652400018** [Aopolin-Lv/ECSpell#1]
你好，看了作者的论文，觉得思路非常不错。
请问可以提供预训练的模型吗？
训练的步骤能否写的具体一些？

**Comment by aopolin-lv** [comment]
很高兴我们的工作得到您的认可, 关于您的问题：
1.预训练模型的参数文件我们会之后以链接的形式附加到repo内
2.我们的训练分为两步：
  a.在大规模无标注预料上使用ecm策略进行pretrain，任务是bertfortokenclassification; 
  b.如果是zero-shot任务的话就结束，否则在相应的训练集上进行train

**Comment by wn1652400018** [comment]
十分感谢回复，请问代码中包含无标记数据预训练的部分吗？
期待作者更新repo。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月30日(周三) 上午10:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Aopolin-Lv/ECSpell] 作者能提供预训练的模型吗 (Issue #1)




 
很高兴我们的工作得到您的认可, 关于您的问题：
 1.预训练模型的参数文件我们会之后以链接的形式附加到repo内
 2.我们的训练分为两步：
 a.在大规模无标注预料上使用ecm策略进行pretrain，任务是bertfortokenclassification;
 b.如果是zero-shot任务的话就结束，否则在相应的训练集上进行train

**Comment by aopolin-lv** [comment]
非常抱歉，我们的预训练相关代码在另外一个分支上，稍后我们会进行合并，请留意repo动态

**Comment by wn1652400018** [comment]
感谢，十分期待您的更新。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月30日(周三) 中午11:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Aopolin-Lv/ECSpell] 作者能提供预训练的模型吗 (Issue #1)




 
非常抱歉，我们的预训练相关代码在另外一个分支上，稍后我们会进行合并，请留意repo动态

**Comment by aopolin-lv** [comment]
> 感谢，十分期待您的更新。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年3月30日(周三) 中午11:04 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Aopolin-Lv/ECSpell] 作者能提供预训练的模型吗 (Issue #1) 非常抱歉，我们的预训练相关代码在另外一个分支上，稍后我们会进行合并，请留意repo动态 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

仓库已经更新了相关的模型权重，请留意
