### ISSUE TITLE
confusion set 细节问题请教

### ISSUE THREAD

**Issue by LiyiLily** [Aopolin-Lv/ECSpell#10]
您好，我对您论文中的混淆构建比较感兴趣，有些问题想请教一下。
请问论文中提到的single character confusion set是使用现有的混淆集还是您自己构建的呢？我看论文里详细介绍了N-gram 的混淆集构建方式，没有提及single character的混淆集。
我在 /ECSpell/Data/confusion 文件夹下看到了几个混淆集文件，其中shapeConfusion.json，soundConfusion.json，NCU_NLPLab_ConfusionSet.txt均为single character混淆集，但是我仔细对比发现它们和常用的sighan2013数据集提供的字音字形混淆集均不一致，可否介绍一下single character混淆集的构建方式呢？

**Comment by aopolin-lv** [comment]
single character混淆集是由spellgcn构建的 [https://github.com/ACL2020SpellGCN/SpellGCN/blob/master/data/gcn_graph.ty_xj/spellGraphs.txt](url)
