### ISSUE TITLE
关于通用任务上的微调细节

### ISSUE THREAD

**Issue by SeaEagleI** [Aopolin-Lv/ECSpell#12]
如题，我基于作者发布的预训练权重折腾了好几天终于跑通了，但不论是在sighan/train.txt上还是在nlg/train.txt上微调，模型在test2015.txt上的评测结果均比作者论文中公布的`{"df1": 81.0, "cf1": 79.5}`低约10个点，想问下是我的配置有什么问题吗？

这两次均加载了ecspell预训练权重，使用了pinyin，使用了默认全名词词表文件，但没有加载word_features，没有用ASM和RSM。两次微调的train.txt和val.txt均是运行tokenize_sequence.py获得，区别在于train_files和val_files不同：第一次使用sighan默认的6476条数据微调，第二次则是使用nlg生成的271329条伪平行数据。

这两次微调的script全部参数如下：
```
export DIR=.
export MODEL_NAME=glyce
export FONT_TYPE=sim
export CHECKPOINT=./checkpoint/ecspell

python $DIR/Code/train_baseline.py \
	--model_name $DIR/Transformers/${MODEL_NAME} \
	--train_files $DIR/Data/traintest/${FONT_TYPE}/${MODEL_NAME}/SIGHAN/train.txt \
	--val_files $DIR/Data/traintest/${FONT_TYPE}/${MODEL_NAME}/SIGHAN/val.txt \
	--test_files $DIR/csc_evaluation/data/basedata/simplified/test2015.txt \
	--cached_dir $DIR/Cache \
	--result_dir $DIR/Results \
	--glyce_config_path $DIR/Transformers/glyce_bert_both_font.json \
	--vocab_file $DIR/Data/vocab/allNoun.txt \
	--load_pretrain_checkpoint ${CHECKPOINT} \
	--font_type ${FONT_TYPE} \
	--overwrite_cached True \
	--num_train_epochs 20 \
	--gradient_accumulation_steps 2 \
	--use_pinyin True \
	--use_word_feature False \
	--use_copy_label False \
	--compute_metrics True \
	--per_device_train_batch_size 32 \
	--per_device_eval_batch_size 64 \
	--save_steps 200 \
	--logging_steps 200 \
	--fp16 True \
	--do_test True \
```
```
export DIR=.
export MODEL_NAME=glyce
export FONT_TYPE=sim
export CHECKPOINT=./checkpoint/ecspell

python $DIR/Code/train_baseline.py \
	--model_name $DIR/Transformers/${MODEL_NAME} \
	--train_files $DIR/Data/traintest/${FONT_TYPE}/${MODEL_NAME}/nlg/train.txt \
	--val_files $DIR/Data/traintest/${FONT_TYPE}/${MODEL_NAME}/nlg/val.txt \
	--test_files $DIR/csc_evaluation/data/basedata/simplified/test2015.txt \
	--cached_dir $DIR/Cache \
	--result_dir $DIR/Results \
	--glyce_config_path $DIR/Transformers/glyce_bert_both_font.json \
	--vocab_file $DIR/Data/vocab/allNoun.txt \
	--load_pretrain_checkpoint ${CHECKPOINT} \
	--font_type ${FONT_TYPE} \
	--overwrite_cached True \
	--num_train_epochs 20 \
	--gradient_accumulation_steps 2 \
	--use_pinyin True \
	--use_word_feature False \
	--use_copy_label False \
	--compute_metrics True \
	--per_device_train_batch_size 32 \
	--per_device_eval_batch_size 64 \
	--save_steps 200 \
	--logging_steps 200 \
	--fp16 True \
	--do_test True \
```

笔者最近正做csc这块的调研，这个项目的复现对我的研究很重要，希望看到这个问题的诸位能提点意见，我在这里提前谢谢大家了！

**Comment by aopolin-lv** [comment]
我们的完整训练过程如下：
1. 使用ecspell的权重初始化model，在nlg的train上做finetune
2. 使用nlg上训练好的model权重初始化，继续在sighan的train上做finetune  
请检查一下训练过程是否一致

**Comment by SeaEagleI** [comment]
> 我们的完整训练过程如下：
> 
> 1. 使用ecspell的权重初始化model，在nlg的train上做finetune
> 2. 使用nlg上训练好的model权重初始化，继续在sighan的train上做finetune
>    请检查一下训练过程是否一致

感谢作者大大，没想到居然秒回了。震惊~
您这么说我就明白了，原来是做了post-training。我会再按您说的重新尝试下的。
不过您说的这些论文和repo里是不是都没提过呀，这README也忒不全了，建议有空补全复现的关键过程吧，不然大家复现起来确实有难度。

**Comment by aopolin-lv** [comment]
非常感谢你的建议，之前传代码的时候确实很仓促。之后又是连续的投稿任务，所以时间上来不及系统整理代码。不过最近我已经在完善之前的工作，预计近两周完成相关代码的整理。另外，我们也在近期会发布一个新的视频理解任务的工作，欢迎star! :)

**Comment by aopolin-lv** [comment]
> 非常感谢你的建议，之前传代码的时候确实很仓促。之后又是连续的投稿任务，所以时间上来不及系统整理代码。不过最近我已经在完善之前的工作，预计近两周完成相关代码的整理。另外，我们也在近期会发布一个新的视频理解任务的工作，欢迎star! :)

关于训练过程，我们在论文的第二个版本中也增加了相关描述，目前还在审稿返修中。之后我们会在arxiv上 更新论文。

**Comment by SeaEagleI** [comment]
> 我们的完整训练过程如下：
> 
> 1. 使用ecspell的权重初始化model，在nlg的train上做finetune
> 2. 使用nlg上训练好的model权重初始化，继续在sighan的train上做finetune
>    请检查一下训练过程是否一致

按您说的训练完了，还是低1.x个点。
详细结果如下：
```
{'test_dacc': 0.8536, 'test_dpre': 0.7878, 'test_drec': 0.8081, 'test_df1': 0.7978, 'test_cacc': 0.8436, 'test_cpre': 0.768, 'test_crec': 0.7878, 'test_cf1': 0.7778, 'test_runtime': 39.4642, 'test_samples_per_second': 27.873, 'epoch': 19.8}
```
而论文里ECSPELL#在test2015上的结果是：
```
{'df1': 81.0, 'cf1': 79.5}
```

**Comment by aopolin-lv** [comment]
> > 我们的完整训练过程如下：
> > 
> > 1. 使用ecspell的权重初始化model，在nlg的train上做finetune
> > 2. 使用nlg上训练好的model权重初始化，继续在sighan的train上做finetune
> >    请检查一下训练过程是否一致
> 
> 按您说的训练完了，还是低1.3个点。 详细结果如下：
> 
> ```
> {'test_dacc': 0.8536, 'test_dpre': 0.7878, 'test_drec': 0.8081, 'test_df1': 0.7978, 'test_cacc': 0.8436, 'test_cpre': 0.768, 'test_crec': 0.7878, 'test_cf1': 0.7778, 'test_runtime': 39.4642, 'test_samples_per_second': 27.873, 'epoch': 19.8}
> ```
> 
> 而论文里ECSPELL#在test2015上的结果是：
> 
> ```
> {'df1': 81.0, 'cf1': 79.5}
> ```

根据我们的经验，finetune所需要的epoch数量较多。实际上，我们在实验中是对两个阶段都使用了epoch=100的设置，选取其最佳cf1的ckpt作为最后的训练权重。我建议您先尝试增加sighan数据集上finetune的epoch轮数。
