### ISSUE TITLE
关于processor.py的疑问

### ISSUE THREAD

**Issue by xdnjust** [Aopolin-Lv/ECSpell#14]
作者你好，我关注了您的修改历史，发现processor.py中的VocabProcessor将add_feature()功能函数去除了，这里出现问题：

1. pipeline.py中tagger()函数第51行还是会调用add_feature()功能
2. pipeline.py中customize函数中的vocab_feature就是由上一步的add_feature()函数生成的

请问作者，这里是不是需要重新更新一下代码

**Comment by aopolin-lv** [comment]
谢谢提醒，已修复
