### ISSUE TITLE
有若干问题想咨询。

### ISSUE THREAD

**Issue by 70557dzqc** [Aopolin-Lv/ECSpell#16]
1. 请问您预训练出来的模型能放出来吗？因为我在github上没找到。
2. 请问您的模型能进行相关的改造，然后解决输入输出不等长的形式吗？比如输入：急昂来的事说不准；输出：将来的事说不准。此时应该把急昂修改成将。

**Comment by aopolin-lv** [comment]
您好，首先感谢您的关注，下面会对您的问题做出回复：
1. repo中是有model weights的链接，模型的权重可以自行下载获取；
2. CSC任务的设定默认是输入输出为等长序列，如果要解决非等长序列的问题可以参照gec相关的技术方案。
