### ISSUE TITLE
关于domain纠错的评估

### ISSUE THREAD

**Issue by nghuyong** [Aopolin-Lv/ECSpell#17]
感谢作者贡献了垂类的纠错数据，请教一下，论文中在这些垂类的指标，是直接用通用领域的模型zero-shot得到吗？还是在垂类几千条数据上也finetune了

**Comment by aopolin-lv** [comment]
您好，是直接zero-shot得到的。

**Comment by ketour** [comment]
![图片](https://github.com/user-attachments/assets/d5a7e951-d607-4c88-82d7-ef2c22d57141)
请问这个表中SpellGCN和SM BERT的指标是在对应领域数据上FT的么？

**Comment by ketour** [comment]
> 您好，是直接zero-shot得到的。

请问论文中SpellGCN和SM BERT的指标都是zero-shot的，并没有在对应领域数据上FT么？

**Comment by aopolin-lv** [comment]
是的，没有FT

**Comment by aopolin-lv** [comment]
> > 您好，是直接zero-shot得到的。
> 
> 请问论文中SpellGCN和SM BERT的指标都是zero-shot的，并没有在对应领域数据上FT么？

是的，没有FT
