### ISSUE TITLE
class PinyinProcessor init 的资料来源可以提供吗

### ISSUE THREAD

**Issue by nicknamechiou** [Aopolin-Lv/ECSpell#2]
作者你好，目前在尝试使用 ECSpell
但是部分资料像是 PinyinProcessor init 时的 pinyin2id.json
或是 train_baseline.py 里面的资料，找不到出处
可以请您提供吗?
谢谢

**Comment by aopolin-lv** [comment]
十分感谢您的关注，相关文件已经更新，请再尝试一下

**Comment by nicknamechiou** [comment]
感谢您的更新
再让我问一下 torchtext 跟 torch 版本好像对不上
会有影响吗
https://pypi.org/project/torchtext/

**Comment by aopolin-lv** [comment]
> 感谢您的更新 再让我问一下 torchtext 跟 torch 版本好像对不上 会有影响吗 https://pypi.org/project/torchtext/

这个应该是没有影响的，如果您无法复线论文中结果，也欢迎继续讨论
