### ISSUE TITLE
使用提供的Model Weights无法复现SIGHAN上的结果

### ISSUE THREAD

**Issue by iioSnail** [Aopolin-Lv/ECSpell#20]
我尝试使用readme中提供的[Model Weight](https://drive.google.com/file/d/1HlfDbMpXR6YHiBuJS8s_K3ZKG6j0fvc5/view?usp=sharing)在SIGHAN2015上进行评估，但结果很差，F1只有45

请问该模型是论文中提到的在SIGHAN15上达到79.5的模型吗？还是我复现的有问题

**Comment by aopolin-lv** [comment]
你好，链接提供的model weight是经过预训练的；如果想在SIGHAN上复现结果的话，需要使用该权重初始化模型并先于Wang271k数据集上微调，再在SIGHAN2013-2015训练集上微调
