### ISSUE TITLE
代码无法跑通，貌似缺少文件

### ISSUE THREAD

**Issue by wn1652400018** [Aopolin-Lv/ECSpell#3]
我已经将glyce等依赖报安装好了，然后执行了shell脚本，发现需要的训练数据集没有。脚本中写着“Data/traintest/sim/glyce/SIGHAN/train.txt”,然后仓库里根本没有这个目录和文件；

然后发现目录/csc_evaluation/builds/sim)/SIGHAN/下有train.txt和val.txt,然后我尝试自己创建Data/traintest/sim/glyce/SIGHAN目录，并把两个文件放进去，执行时发现 [  train_texts, train_tags, val_texts, val_tags, labels, tag2id = load_data(args)](https://github.com/Aopolin-Lv/ECSpell/blob/3c760d103d4433c03c79007bc4d752c068d4744c/Code/train_baseline.py#L271)这一行结果是错的，我仔细查看了内部代码，发现该代码貌似不是处理我找到的train.txt文件。这一点希望作者检查一下是不是缺少数据。

虽然该行代码有问题，但是没有报错。知道运行至[ model = ECSpell(glyce_config, processor.pinyin_processor.get_pinyin_size(), len(labels), True)]https://github.com/Aopolin-Lv/ECSpell/blob/3c760d103d4433c03c79007bc4d752c068d4744c/Code/train_baseline.py#L271这里时报错了：OSError: Error no file named pytorch_model.bin found in directory ECSpell/Transformers/glyce
除此之外，自己解决了一些其它不是很重要的问题。
希望作者抽空检查一下，提供一下缺失的文件，最好能够将仓库的代码自己运行成功。

**Comment by aopolin-lv** [comment]
您好，```Data/traintest/```是由Code/tokenize_sequence.py创建的，model的weight已经上传至google driver，需要手动下载mv至相应目录。另外repo上传的比较匆忙，给您带来了不便，之后我会找时间整理代码，另外进行更新，不好意思。

**Comment by wn1652400018** [comment]
我下载了权重的压缩包，发现里面有两个文件夹，一个是bert一个是glyce，两个里面都有torch_model.bin文件，不知要用哪一个。而且两个文件好像是checkpoint文件，应该不是原始的没有训练过的模型权重吧。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月17日(周二) 中午11:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Aopolin-Lv/ECSpell] 代码无法跑通，貌似缺少文件 (Issue #3)




 
您好，Data/traintest/是由Code/tokenize_sequence.py创建的，model的weight已经上传至google driver，需要手动下载mv至相应目录。另外repo上传的比较匆忙，给您带来了不便，之后我会找时间整理代码，另外进行更新，不好意思。

**Comment by aopolin-lv** [comment]
这两个分别是bert/ecspell model经过我们文章中提到的pretraining所得到的权重
