### ISSUE TITLE
预训练代码

### ISSUE THREAD

**Issue by xdnjust** [Aopolin-Lv/ECSpell#5]
楼主大佬您好，

我们教研室重点分析了您的文章，觉得思路创新非常棒，老师希望我们能复现一下结果

请问一下预训练那块的代码有开源计划吗？我看您在其他ISSUE回复有这个计划

**Comment by aopolin-lv** [comment]
> 楼主大佬您好，
> 
> 我们教研室重点分析了您的文章，觉得思路创新非常棒，老师希望我们能复现一下结果
> 
> 请问一下预训练那块的代码有开源计划吗？我看您在其他ISSUE回复有这个计划

抱歉回复的晚了一些，预训练的核心逻辑是错误一致性掩码策略，现在已经更新。
另外时间比较仓促，如果代码中出现问题，请及时继续交流

**Comment by xdnjust** [comment]
@Aopolin-Lv 谢谢楼主的回复，针对中文纠错的掩码策略真的很不错，提供了很多研究思路

有两个问题确认一下：

1. 在“Code/DataAugment/fake_data.py”的第291行(freq_filename = r'Data/fakedata/new2016zh/vocab.txt')，这个文件好像没有上传？请楼主看一下
2. 在“Code/DataAugment/fake_data.py”的fake_continuous()函数最后返回的index，函数中没有赋值，返回为[]，这是不是有问题？
3. 文件夹“Data/confusion/”中包含许多confusion set数据集（比如shapeConfusion.json、soundConfusion.json、spellGraph.txt），但是fake_data.py中好像只用到了spellGraph.txt，其它的数据集是不需要用吗？
4. 请教一下预训练是用的什么方法？直接采用开源的BERT预训练任务来做的吗？我没找到相关代码位置

谢谢！

**Comment by aopolin-lv** [comment]
1. 很抱歉这个上传时遗漏了，该文件是统计`new2016zh`文件中所有单独的字并最后形成size为17894的词表。该文件可以先自行生成，另外我们预计会有在1-2周内对仓库更新
2. 这个对整体应该是不影响的
3. 是的
4. 这里的预训练实际上是task-specific pretraining，是做是和finetune一致的任务

**Comment by HeartSea15** [comment]
1. 您好，上面问题的第一条问题，“该文件是统计new2016zh文件中所有单独的字并最后形成size为17894的词表。该文件可以先自行生成”，这个用什么方法生成呢，可以更新下代码仓库吗，谢谢。
只需要统计中文字吗，还是所有的单独的字，包括英文字母，标点符号呢，最后是一个字符和一个词频对吧。
