### ISSUE TITLE
数据集缺失

### ISSUE THREAD

**Issue by wn1652400018** [Aopolin-Lv/ECSpell#7]
sh文件中看到要使用一下文件，作者好像没有上传。能补传一下吗？

export MODEL_NAME=glyce
export FONT_TYPE=sim

--train_files $DIR/Data/traintest/${FONT_TYPE}/${MODEL_NAME}/SIGHAN/train.txt \
--val_files $DIR/Data/traintest/${FONT_TYPE}/${MODEL_NAME}/SIGHAN/val.txt \

**Comment by aopolin-lv** [comment]
这部分的文件可以通过tokenize_sequence.py获取

**Comment by wn1652400018** [comment]
我需要自己去下载sighan的训练集和评估集，再执行tokenize_sequence.py就可以了吗。

**Comment by aopolin-lv** [comment]
是的

**Comment by aopolin-lv** [comment]
> 我需要自己去下载sighan的训练集和评估集，再执行tokenize_sequence.py就可以了吗。

抱歉之前的回复错误，训练的相关数据可以在`csc_evaluation/data/basedata`获取
