### ISSUE TITLE
User Dictionary Guided Framework问题请教

### ISSUE THREAD

**Issue by xdnjust** [Aopolin-Lv/ECSpell#9]
作者您好，请教2个问题：

1. RSM和ASM的中文理解是什么，我看论文还不是很明白
2. 这两个方法应该不需要训练吧，只是推理时候作为一种增强性能的方法？
3. 代码中关于RSM和ASM在哪里，是pipeline.py中的customize()函数吗？我没有理解在哪块实现了ASM

抱歉问题有点多，请作者答疑

**Comment by aopolin-lv** [comment]
1. RSM和ASM可以认为是在inference时搜索最优结果的策略，具体做法是通过对模型给出的candidate path进行重新打分
2. 是的
3. 是的, 可以参照pipeline.py中line 140

**Comment by xdnjust** [comment]
@Aopolin-Lv 感谢回复，再请教一下：
1. evalute.py第138行的labels.txt是指的什么？是类似于BERT预训练模型自带的vocab.txt文件吗？如果是的话，为啥不直接用vocab.txt
2. pipeline.py第138行，当j=0时，是不是会出现边界溢出问题？这里代码是不是写错了
3. process.py第31行的VocabProcessor是针对User Dictionary进行处理的类吗？add_feature()函数的作用是什么？

**Comment by aopolin-lv** [comment]
> @Aopolin-Lv 感谢回复，再请教一下：
> 
> 1. evalute.py第138行的labels.txt是指的什么？是类似于BERT预训练模型自带的vocab.txt文件吗？如果是的话，为啥不直接用vocab.txt
> 2. pipeline.py第138行，当j=0时，是不是会出现边界溢出问题？这里代码是不是写错了
> 3. process.py第31行的VocabProcessor是针对User Dictionary进行处理的类吗？add_feature()函数的作用是什么？

1. 我们的模型在最后分类的时候，词表是做过裁切的。由于原先bert vocab大小为21128的词表维度较大并且其中有很多非中文字，实际分布是较为稀疏的，所以我们对词表进行了裁切。具体这个labels.txt，是我们统计了论文中pretrain阶段语料的中文字符频率，选取其top6000所构成的
2. 我们在程序运行中，暂时没发现这个问题。如果方便的话，可以把case分享一下，我们也好进一步完善代码
3. 是的；在默认的脚本中，该方法不启用不影响主程序

**Comment by xdnjust** [comment]
@Aopolin-Lv 
1. 上面第二个问题，第138行“src_id = tag2id[src[j - 1]] if src[j - 1] in tag2id.keys() else tag2id["<unk>"]” 这里当j=0的时候，j-1=-1，也就是取src的最后一个值吗？这段代码的意思是什么？为啥取j-1而不是取j
2. 我们团队对您的方法很感兴趣，想深入分析，能否补齐一下代码中一些缺失的文件，这样可以直接调试？现在一直打扰您很是抱歉

**Comment by aopolin-lv** [comment]
> @Aopolin-Lv
> 
> 1. 上面第二个问题，第138行“src_id = tag2id[src[j - 1]] if src[j - 1] in tag2id.keys() else tag2id[""]” 这里当j=0的时候，j-1=-1，也就是取src的最后一个值吗？这段代码的意思是什么？为啥取j-1而不是取j
> 2. 我们团队对您的方法很感兴趣，想深入分析，能否补齐一下代码中一些缺失的文件，这样可以直接调试？现在一直打扰您很是抱歉

非常抱歉目前代码可能还存在一些问题，我们在2-3周之后会统一再整理。如果遇到有意思的问题欢迎一起讨论。

**Comment by xdnjust** [comment]
@Aopolin-Lv 谢谢，关于User Dictionary的处理类VocabProcessor （process.py第31行），还请帮忙指导一下：
1. 其中的函数add_feature()的作用是什么？
2. 函数add_feature()中的token2text、text2token、text2sent、sent2text的含义是什么？
3. 关于预训练那块，请问一下你们是跑了多少个epoch达到论文的效果的

**Comment by aopolin-lv** [comment]
1. add_feature()是做了其他实验的代码，目前已移除
2. 参照1
3. 论文中有介绍，我们预训练跑了150k step 选取cf1最大的ckpt作为最终结果
